language: python

python:
  - 2.7

env:
  - CPLUS_INCLUDE_PATH=/usr/include/gdal C_INCLUDE_PATH=/usr/include/gdal

before_install:
  - sudo apt-get update
  - sudo apt-get install gdal-bin libgdal-dev python-dev build-essential libjpeg-dev libjpeg8-dev libpng3 libfreetype6-dev python-mapnik mapnik-input-plugin-gdal mapnik-input-plugin-ogr mapnik-input-plugin-osm mapnik-input-plugin-postgis mapnik-input-plugin-sqlite mapnik-utils libmapnik2.2 libmapnik2-dev postgresql-9.3-postgis-2.1
  - pip install --allow-external --allow-insecure --find-links http://wheels2.astropy.org/ --use-wheel "Cython>=0.16" Numpy "matplotlib>=1.2.1" "GDAL>=1.10.0" PIL --allow-external PIL --allow-unverified PIL --allow-all-external --allow-unverified elementtree elementtree virtualenvwrapper virtualenv
  - sudo -u postgres psql -d template1 -c "CREATE EXTENSION postgis;"
  - sudo -u postgres psql -d template1 -f madrona/common/sql/cleangeometry.sql
  - sudo -u postgres createuser -sdP django
  - sudo -u postgres createdb -O django test_project

install:
  - pip install -r requirements.txt --use-mirrors
  - pip install -r requirements-dev.txt --use-mirrors
  - python setup.py install

script:
  - python utils/run_tests.py

# after_success:
#   - coveralls
